create table bnd_dw22bnd1_1(
    dw_bnd1_acdate date not null,
    dw_bnd1_delta_flag nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_bank nvarchar(3) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_sec_code nvarchar(12) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_dyn_status_val1 nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_dyn_status_val2 nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_dyn_status_val3 nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_dyn_status_val4 nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_dyn_status_val5 nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_dyn_status_val6 nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_dyn_status_val7 nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_dyn_status_val8 nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_sec_type nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_sec_name  nvarchar(32) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_issuer nvarchar(4) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_issuer_type nvarchar(2) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_guarantor nvarchar(4) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_risk_nation nvarchar(2) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_issue_date date null,
    dw_bnd1_mature_date date null,
    dw_bnd1_cpn_date1  nvarchar(4) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_cpn_date2  nvarchar(4) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_cpn_date3  nvarchar(4) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_cpn_date4  nvarchar(4) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_cpn_rate date null,
    dw_bnd1_dayinfo  nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_divisor  nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_sec_curr nvarchar(3) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_sec_desc  nvarchar(50) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_fcpn_date date null,
    dw_bnd1_scpn_date date null,
    dw_bnd1_ncpn_date date null,
    dw_bnd1_denom decimal(13,2) not null,
    dw_bnd1_taxrate decimal(5,2) not null,
    dw_bnd1_min_int decimal(9,6) not null,
    dw_bnd1_max_int decimal(9,6) not null,
    dw_bnd1_min_txamt decimal(9,6) not null,
    dw_bnd1_inctxamt decimal(9,6) not null,
    dw_bnd1_vad_ind  nvarchar(3) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_call nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_put nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_status_01 nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_serchg_cls nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_redeem_price decimal(11,7) not null,
    dw_bnd1_cpn_defn nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_option_date1_1 date null,
    dw_bnd1_option_date1_2 date null,
    dw_bnd1_option_date1_3 date null,
    dw_bnd1_option_date1_4 date null,
    dw_bnd1_option_date1_5 date null,
    dw_bnd1_option_date1_6 date null,
    dw_bnd1_option_date1_7 date null,
    dw_bnd1_option_date1_8 date null,
    dw_bnd1_option_date1_9 date null,
    dw_bnd1_option_date1_10 date null,
    dw_bnd1_option_date1_11 date null,
    dw_bnd1_option_date1_12 date null,
    dw_bnd1_option_price1_1 date null,
    dw_bnd1_option_price1_2 date null,
    dw_bnd1_option_price1_3 date null,
    dw_bnd1_option_price1_4 date null,
    dw_bnd1_option_price1_5 date null,
    dw_bnd1_option_price1_6 date null,
    dw_bnd1_option_price1_7 date null,
    dw_bnd1_option_price1_8 date null,
    dw_bnd1_option_price1_9 date null,
    dw_bnd1_option_price1_10 date null,
    dw_bnd1_option_price1_11 date null,
    dw_bnd1_option_price1_12 date null,

)