create table batch_step_execution(
    step_execution_id bigint not null,
    version bigint not null,
    step_name nvarchar(100) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    job_execution_id bigint not null,
    create_time datetime not null,
    start_time datetime default null,
    end_time datetime default null,
    status nvarchar(10) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    commit_count bigint null,
    read_count bigint null,
    filter_count bigint null,
    write_count bigint null,
    read_skip_count bigint null,
    write_skip_count bigint null,
    process_skip_count bigint null,
    rollback_count bigint null,
    exit_code nvarchar(2500) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    exit_message nvarchar(2500) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    last_updated datetime null
)