create table bnd_dw22bnd1_1(
    dw_bnd1_acdate date not null,
    dw_bnd1_delta_flag nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_bank nvarchar(3) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_sec_code nvarchar(12) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_dyn_status_val1 nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_dyn_status_val2 nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_dyn_status_val3 nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_dyn_status_val4 nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_dyn_status_val5 nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_dyn_status_val6 nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_dyn_status_val7 nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_dyn_status_val8 nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_sec_type nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_sec_name  nvarchar(32) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_issuer nvarchar(4) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_issuer_type nvarchar(2) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_guarantor nvarchar(4) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_risk_nation nvarchar(2) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_issue_date date null,
    dw_bnd1_mature_date date null,
    dw_bnd1_cpn_date1  nvarchar(4) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_cpn_date2  nvarchar(4) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_cpn_date3  nvarchar(4) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_cpn_date4  nvarchar(4) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_cpn_rate date null,
    dw_bnd1_dayinfo  nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_divisor  nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_sec_curr nvarchar(3) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_sec_desc  nvarchar(50) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_fcpn_date date null,
    dw_bnd1_scpn_date date null,
    dw_bnd1_ncpn_date date null,
    dw_bnd1_denom decimal(13,2) not null,
    dw_bnd1_taxrate decimal(5,2) not null,
    dw_bnd1_min_int decimal(9,6) not null,
    dw_bnd1_max_int decimal(9,6) not null,
    dw_bnd1_min_txamt decimal(9,6) not null,
    dw_bnd1_inctxamt decimal(9,6) not null,
    dw_bnd1_vad_ind  nvarchar(3) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_call nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_put nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_status_01 nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_serchg_cls nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_redeem_price decimal(11,7) not null,
    dw_bnd1_cpn_defn nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_option_date1_1 date null,
    dw_bnd1_option_date1_2 date null,
    dw_bnd1_option_date1_3 date null,
    dw_bnd1_option_date1_4 date null,
    dw_bnd1_option_date1_5 date null,
    dw_bnd1_option_date1_6 date null,
    dw_bnd1_option_date1_7 date null,
    dw_bnd1_option_date1_8 date null,
    dw_bnd1_option_date1_9 date null,
    dw_bnd1_option_date1_10 date null,
    dw_bnd1_option_date1_11 date null,
    dw_bnd1_option_date1_12 date null,
    dw_bnd1_option_price1_1 date null,
    dw_bnd1_option_price1_2 date null,
    dw_bnd1_option_price1_3 date null,
    dw_bnd1_option_price1_4 date null,
    dw_bnd1_option_price1_5 date null,
    dw_bnd1_option_price1_6 date null,
    dw_bnd1_option_price1_7 date null,
    dw_bnd1_option_price1_8 date null,
    dw_bnd1_option_price1_9 date null,
    dw_bnd1_option_price1_10 date null,
    dw_bnd1_option_price1_11 date null,
    dw_bnd1_option_price1_12 date null,
    dw_bnd1_ann_date1  date not null,
    dw_bnd1_call_per1  decimal(5,2) not null,
    dw_bnd1_option_date2_1 date null,
    dw_bnd1_option_date2_2 date null,
    dw_bnd1_option_date2_3 date null,
    dw_bnd1_option_date2_4 date null,
    dw_bnd1_option_date2_5 date null,
    dw_bnd1_option_date2_6 date null,
    dw_bnd1_option_date2_7 date null,
    dw_bnd1_option_date2_8 date null,
    dw_bnd1_option_date2_9 date null,
    dw_bnd1_option_date2_10 date null,
    dw_bnd1_option_date2_11 date null,
    dw_bnd1_option_date2_12 date null,
    dw_bnd1_option_price2_1 date null,
    dw_bnd1_option_price2_2 date null,
    dw_bnd1_option_price2_3 date null,
    dw_bnd1_option_price2_4 date null,
    dw_bnd1_option_price2_5 date null,
    dw_bnd1_option_price2_6 date null,
    dw_bnd1_option_price2_7 date null,
    dw_bnd1_option_price2_8 date null,
    dw_bnd1_option_price2_9 date null,
    dw_bnd1_option_price2_10 date null,
    dw_bnd1_option_price2_11 date null,
    dw_bnd1_option_price2_12 date null,
    dw_bnd1_ann_date2  date not null,
    dw_bnd1_call_per2  decimal(5,2) not null,
    dw_bnd1_ai_type1  nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_refdate1  date not null,
    dw_bnd1_ai_lcpdate1  date null,
    dw_bnd1_ai_intday1  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_ldate1  date null,
    dw_bnd1_ai_ltime1  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_receipt1  nvarchar(3) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_type2  nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_refdate2  date not null,
    dw_bnd1_ai_lcpdate2  date null,
    dw_bnd1_ai_intday2  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_ldate2  date null,
    dw_bnd1_ai_ltime2  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_receipt2  nvarchar(3) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_type3  nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_refdate3  date not null,
    dw_bnd1_ai_lcpdate3  date null,
    dw_bnd1_ai_intday3  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_ldate3  date null,
    dw_bnd1_ai_ltime3  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_receipt3  nvarchar(3) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_type4  nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_refdate4  date not null,
    dw_bnd1_ai_lcpdate4  date null,
    dw_bnd1_ai_intday4  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_ldate4  date null,
    dw_bnd1_ai_ltime4  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_receipt4  nvarchar(3) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_type5  nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_refdate5  date not null,
    dw_bnd1_ai_lcpdate5  date null,
    dw_bnd1_ai_intday5  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_ldate5  date null,
    dw_bnd1_ai_ltime5  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_receipt5  nvarchar(3) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_type6  nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_refdate6  date not null,
    dw_bnd1_ai_lcpdate6  date null,
    dw_bnd1_ai_intday6  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_ldate6  date null,
    dw_bnd1_ai_ltime6  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_receipt6  nvarchar(3) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_type7  nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_refdate7  date not null,
    dw_bnd1_ai_lcpdate7  date null,
    dw_bnd1_ai_intday7  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_ldate7  date null,
    dw_bnd1_ai_ltime7  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_receipt7  nvarchar(3) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_type8  nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_refdate8  date not null,
    dw_bnd1_ai_lcpdate8  date null,
    dw_bnd1_ai_intday8  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_ldate8  date null,
    dw_bnd1_ai_ltime8  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_receipt8  nvarchar(3) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_type9  nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_refdate9  date not null,
    dw_bnd1_ai_lcpdate9  date null,
    dw_bnd1_ai_intday9  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_ldate9  date null,
    dw_bnd1_ai_ltime9  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_receipt9  nvarchar(3) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_type10  nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_refdate10  date not null,
    dw_bnd1_ai_lcpdate10  date null,
    dw_bnd1_ai_intday10  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_ldate10  date null,
    dw_bnd1_ai_ltime10  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_receipt10  nvarchar(3) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_type11  nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_refdate11  date not null,
    dw_bnd1_ai_lcpdate11  date null,
    dw_bnd1_ai_intday11  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_ldate11  date null,
    dw_bnd1_ai_ltime11  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_receipt11  nvarchar(3) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_type12  nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_refdate12  date not null,
    dw_bnd1_ai_lcpdate12  date null,
    dw_bnd1_ai_intday12  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_ldate12  date null,
    dw_bnd1_ai_ltime12  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_receipt12  nvarchar(3) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_type13  nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_refdate13  date not null,
    dw_bnd1_ai_lcpdate13  date null,
    dw_bnd1_ai_intday13  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_ldate13  date null,
    dw_bnd1_ai_ltime13  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_receipt13  nvarchar(3) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_type14  nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_refdate14  date not null,
    dw_bnd1_ai_lcpdate14  date null,
    dw_bnd1_ai_intday14  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_ldate14  date null,
    dw_bnd1_ai_ltime14  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_receipt14  nvarchar(3) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_type15  nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_refdate15  date not null,
    dw_bnd1_ai_lcpdate15  date null,
    dw_bnd1_ai_intday15  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_ldate15  date null,
    dw_bnd1_ai_ltime15  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_receipt15  nvarchar(3) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_type16  nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_refdate16  date not null,
    dw_bnd1_ai_lcpdate16  date null,
    dw_bnd1_ai_intday16  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_ldate16  date null,
    dw_bnd1_ai_ltime16  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_receipt16  nvarchar(3) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_type17  nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_refdate17  date not null,
    dw_bnd1_ai_lcpdate17  date null,
    dw_bnd1_ai_intday17  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_ldate17  date null,
    dw_bnd1_ai_ltime17  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_receipt17  nvarchar(3) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_type18  nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_refdate18  date not null,
    dw_bnd1_ai_lcpdate18  date null,
    dw_bnd1_ai_intday18  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_ldate18  date null,
    dw_bnd1_ai_ltime18  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_receipt18  nvarchar(3) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_type19  nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_refdate19  date not null,
    dw_bnd1_ai_lcpdate19  date null,
    dw_bnd1_ai_intday19  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_ldate19  date null,
    dw_bnd1_ai_ltime19  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_receipt19  nvarchar(3) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_type20  nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_refdate20  date not null,
    dw_bnd1_ai_lcpdate20  date null,
    dw_bnd1_ai_intday20  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_ldate20  date null,
    dw_bnd1_ai_ltime20  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_ai_receipt20  nvarchar(3) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_pcode  nvarchar(6) collate Latin1_General_100_CI_AS_SC_UTF8  null,
    dw_bnd1_fixed_acc_int decimal(17,6) not null,
    dw_bnd1_cpn_freq  nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8 not null,
    dw_bnd1_credit_rating  nvarchar(10) collate Latin1_General_100_CI_AS_SC_UTF8  not null,
    dw_bnd1_product_type  nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8  not null,
    dw_bnd1_pri_placement  nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8  not null,
    dw_bnd1_risk_rating  nvarchar(1) collate Latin1_General_100_CI_AS_SC_UTF8  not null,

)